language: java
jdk:
  - oraclejdk8

script: "[ ${TRAVIS_PULL_REQUEST} = 'false' ] && mvn clean deploy --settings settings.xml || mvn clean verify --settings settings.xml"

cache:
  directories:
    - $HOME/.m2
